import './globals.css'
import { Montserrat } from 'next/font/google'
import Navbar from '../components/navbar'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-mont bg-light dark:bg-black w-full min-h-screen`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
